server:
  port: 8081
  servlet:
    context-path: /hotelmaster

spring:
  application:
      name: hotelmaster
  datasource:
    url: "jdbc:mysql://localhost:3366/hotelmaster"
    username: root
    password: root
  jpa:
    hibernate:
       ddl-auto: update
    show_sql: true

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds
